GET http://localhost:3000/notes

###
GET http://localhost:3000/notes/a67b06d1-7f7e-11ef-bb58-ca528eb12f7a

###
POST http://localhost:3000/notes
Content-Type: application/json

{
    "sql": "SELECT * FROM users",
    "content": "zod is a powerfull tool for server side type validation",
    "important": true
}

### 
PATCH http://localhost:3000/notes/dffce2a1-81cc-11ef-8991-ca528eb12f7a
Content-Type: application/json 
 
{
    "content": "zod is a powerful tool for type validation",
    "important": true
}

### 
DELETE  http://localhost:3000/notes/7910a026-81cc-11ef-8991-ca528eb12f7a