GET http://localhost:3000/notes

###
GET http://localhost:3000/notes/2b53db2f-dfe9-4e47-b83f-3fafcc9227fb

###
POST http://localhost:3000/notes
Content-Type: application/json

{
    "me cachis en lamar": "this shouldnt work",
    "content": "zod is a powerfull tool for server side type validation",
    "important": false
}

### 
PATCH http://localhost:3000/notes/2b53db2f-dfe9-4e47-b83f-3fafcc9227fb
Content-Type: application/json 

{
    "important": true
}

### 
DELETE  http://localhost:3000/api/notes/2b53db2f-dfe9-4e47-b83f-3fafcc9227fb

